#!/usr/bin/env php
<?php

$options = getopt(
    "s::k:v:d::h", 
    [
        "servers::",
        "driver::",
        "key:",
        "value:",
        "help"
    ],
);

if (isset($options['help']) || isset($options['h'])) {
    echo "memcphset [-s|--servers] <-k|--key> <-v|--value> [-h|--help]";
    exit;
} 

$serverString = $options['servers'] ?? $options['s'] ?? getenv('MEMCACHED_SERVERS') ?: 'localhost';
$key = $options['key'] ?? $options['k'] ?? null;
$value = $options['value'] ?? $options['v'] ?? true;
$driver = $options['driver'] ?? $options['d'] ?? 'memcache';

$hostPortPairs = array_map('trim', explode(',', $serverString));
foreach ($hostPortPairs as $i => $hostPortPair) {
    [$host, $port] = array_map('trim', explode(':', $hostPortPair)) + ['localhost', 11211];
    if (empty($port)) {
        $port = 11211;
    }

    $hostPortPairs[$i] = ['host' => $host, 'port' => $port];
}

if ($driver === 'memcache') {
    $m = new Memcache();
} else {
    $m = new Memcached();
}

foreach ($hostPortPairs as $hostPortPair) {
    $m->addServer($hostPortPair['host'], $hostPortPair['port']);
}

if ($m->set($key, $value)) {
    exit(0);
} else {
    exit(1);
}
